version: '3'
volumes:
  mysql_data:
      driver: local

services:
  kraken:
    build: .
    ports:
      - 8081:8080
    command: run -d -c /etc/krakend/krakend.json
    volumes:
      - ./etc/:/etc/krakend/
    depends_on:
      - nginx
  backend:
      build: backend/
      #volumes:
      #  - ./backend:/code
      #command: tail -f /etc/fstab
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:15.0.2
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql
  nginx:
      image: nginx
      ports:
        - 8085:80
      volumes:
        - ./nginx:/usr/share/nginx/html
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    #volumes:
    #  - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_USERNAME=bn_parse
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=bitnami123
      - MONGODB_ROOT_PASSWORD=rootpassword
  parse:
    image: parseplatform/parse-server
    #volumes:
    #  - 'parse_data:/bitnami/parse'
    depends_on:
      - mongodb
    ports:
      - '1337:1337'
    command: --appId myAppId --masterKey myMasterKey --databaseURI mongodb://bn_parse:bitnami123@mongodb/bitnami_parse
    environment:
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=bn_parse
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=bitnami123
  parse-dashbourd:
    image: parseplatform/parse-dashboard
    ports:
      - '4040:4040'
    #volumes:
    #  - 'parse_data:/bitnami/parse'
    command: --dev
    depends_on:
      - parse
    volumes:
      - ./parse/parse-dashboard.json:/src/Parse-Dashboard/parse-dashboard-config.json   
    environment:
      - PORT=4040
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - ALLOW_INSECURE_HTTP=1
      #- MOUNT_PATH="/parse"







